prologue :- 
    write('The year was 2070, Willy Wangky Theme Park was barely\n'),sleep(0.7),
    write('standing on its leg after having all those years of glory.\n'),sleep(0.7),
    write('Willy tried to upgrade all of his attractions to gain more\n'),sleep(0.7),
    write('visitors, but it was futile. Until the year 2071, where finally \n'),sleep(0.7),
    write('the Theme Park had to closed down.\n'),sleep(0.7),
    write('\n'),sleep(0.7),
    write('But Willy did not surrender, he started to experiment\n'),sleep(0.7),
    write('with magic. It was only a simple mistake from Willy, \n'),sleep(0.7),
    write('but he accidentally opened a portal to another dimension \n'),sleep(0.7),
    write('full of monsters and creatures.\n'),sleep(0.7),
    write('\n'),sleep(0.7),
    write('Not long after the incident, earth was dominated by the \n'),sleep(0.7),
    write('strange creatures. Earth was a mess for 50 years, \n'),sleep(0.7),
    write('you are unfortunately enough to be born in this era.\n'),sleep(0.7),
    write('\n'),sleep(0.7),
    write('Bearing the burden of being Willy Wangky\'s grandchild,\n'),sleep(0.7),
    write('you try to clean up after your grandfather\'s mistakes\n'),sleep(0.7),
    write('and thats where you starts your journey...'),sleep(0.7).